allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects { sub ->
    sub.buildDir = "${rootProject.buildDir}/${sub.name}"
    sub.evaluationDependsOn(':app')
    sub.plugins.withId('com.android.application') {
        if (sub.android.namespace == null) {
            sub.android.namespace = sub.group
        }
    }
    sub.plugins.withId('com.android.library') {
        if (sub.android.namespace == null) {
            sub.android.namespace = sub.group
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.layout.buildDirectory
}
